---
author: "Mark Christopher Adkins"
date: '`r paste("Created: 2020-11-17"," Last Modified: ", format(Sys.Date()))`'
title: 'Test'
output:
  html_document:
    css: "../misc/style.css"
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here("HTML Exercises"))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tippy)
```

To customize the tooltips, check out [https://atomiks.github.io/tippyjs/#all-options](https://atomiks.github.io/tippyjs/#all-options)

```{r echo=FALSE}
tippy("<strong>Hover here!</strong>", 
  tooltip = "This is so cool!", 
  allowHTML = TRUE,
  animation = "scale",
  duration = 1000, 
  placement = "bottom",
  theme = "light",
  arrow = "large"
)
```


:::fyi
This is an FYI.
:::

:::note
This is an note.
:::

:::puzzle
This is a puzzle.
:::

:::demo
This is a demo.
:::

:::grimace
This is a grimace.

Icon is from Font Awesome
[Licencse](https://fontawesome.com/license)
:::

:::example
This is an example.
:::